project 'Spotting.xcodeproj'

platform :ios, '11.0'

target 'Spotting' do
  use_frameworks!

  # Pods for Spotting
  pod 'R.swift', '~> 4.0.0'
  pod 'Cartography', '~> 3.1.0'
  pod 'SwiftFormat/CLI', '~> 0.35.5'
  pod 'microLogger', '~> 1.0.3'

  target 'SpottingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
