//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
    fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
    fileprivate static let hostingBundle = Bundle(for: R.Class.self)

    static func validate() throws {
        try intern.validate()
    }

    /// This `R.color` struct is generated, and contains static references to 0 colors.
    struct color {
        fileprivate init() {}
    }

    /// This `R.file` struct is generated, and contains static references to 0 files.
    struct file {
        fileprivate init() {}
    }

    /// This `R.font` struct is generated, and contains static references to 0 fonts.
    struct font {
        fileprivate init() {}
    }

    /// This `R.image` struct is generated, and contains static references to 1 images.
    struct image {
        /// Image `icon`.
        static let icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon")

        /// `UIImage(named: "icon", bundle: ..., traitCollection: ...)`
        static func icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
            return UIKit.UIImage(resource: R.image.icon, compatibleWith: traitCollection)
        }

        fileprivate init() {}
    }

    /// This `R.nib` struct is generated, and contains static references to 0 nibs.
    struct nib {
        fileprivate init() {}
    }

    /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
    struct reuseIdentifier {
        fileprivate init() {}
    }

    /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
    struct segue {
        fileprivate init() {}
    }

    /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
    struct storyboard {
        /// Storyboard `LaunchScreen`.
        static let launchScreen = _R.storyboard.launchScreen()

        /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
        static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
            return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
        }

        fileprivate init() {}
    }

    /// This `R.string` struct is generated, and contains static references to 1 localization tables.
    struct string {
        /// This `R.string.localizable` struct is generated, and contains static references to 22 localization keys.
        struct localizable {
            /// Value: About app
            static let settingsAbout_app = Rswift.StringResource(key: "settings.about_app", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Change password
            static let settingsChange_password = Rswift.StringResource(key: "settings.change_password", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Confirm password
            static let signup_confirm_password = Rswift.StringResource(key: "signup_confirm_password", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Contact
            static let settingsContact = Rswift.StringResource(key: "settings.contact", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: E-mail
            static let forgotpswd_email = Rswift.StringResource(key: "forgotpswd_email", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: E-mail
            static let signup_email = Rswift.StringResource(key: "signup_email", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Forgot password?
            static let login_forgot_button = Rswift.StringResource(key: "login_forgot_button", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Help
            static let settingsHelp = Rswift.StringResource(key: "settings.help", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Login
            static let login_view_button_title = Rswift.StringResource(key: "login_view_button_title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Logout
            static let settingsLogout = Rswift.StringResource(key: "settings.logout", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Password
            static let login_view_password_placeholder = Rswift.StringResource(key: "login_view_password_placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Password
            static let signup_password = Rswift.StringResource(key: "signup_password", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Privacy policy
            static let settingsPrivacy_policy = Rswift.StringResource(key: "settings.privacy_policy", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Send email
            static let forgotpswd_send_email = Rswift.StringResource(key: "forgotpswd_send_email", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Settings
            static let settingsTitle = Rswift.StringResource(key: "settings.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Sign up
            static let login_signup_button = Rswift.StringResource(key: "login_signup_button", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Sign up
            static let signup_signup_button = Rswift.StringResource(key: "signup_signup_button", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Spots
            static let listTitle = Rswift.StringResource(key: "list.title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Spotting
            static let login_title = Rswift.StringResource(key: "login_title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Username
            static let forgotpswd_username = Rswift.StringResource(key: "forgotpswd_username", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Username
            static let login_view_username_placeholder = Rswift.StringResource(key: "login_view_username_placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
            /// Value: Username
            static let signup_username = Rswift.StringResource(key: "signup_username", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

            /// Value: About app
            static func settingsAbout_app(_: Void = ()) -> String {
                return NSLocalizedString("settings.about_app", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Change password
            static func settingsChange_password(_: Void = ()) -> String {
                return NSLocalizedString("settings.change_password", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Confirm password
            static func signup_confirm_password(_: Void = ()) -> String {
                return NSLocalizedString("signup_confirm_password", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Contact
            static func settingsContact(_: Void = ()) -> String {
                return NSLocalizedString("settings.contact", bundle: R.hostingBundle, comment: "")
            }

            /// Value: E-mail
            static func forgotpswd_email(_: Void = ()) -> String {
                return NSLocalizedString("forgotpswd_email", bundle: R.hostingBundle, comment: "")
            }

            /// Value: E-mail
            static func signup_email(_: Void = ()) -> String {
                return NSLocalizedString("signup_email", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Forgot password?
            static func login_forgot_button(_: Void = ()) -> String {
                return NSLocalizedString("login_forgot_button", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Help
            static func settingsHelp(_: Void = ()) -> String {
                return NSLocalizedString("settings.help", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Login
            static func login_view_button_title(_: Void = ()) -> String {
                return NSLocalizedString("login_view_button_title", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Logout
            static func settingsLogout(_: Void = ()) -> String {
                return NSLocalizedString("settings.logout", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Password
            static func login_view_password_placeholder(_: Void = ()) -> String {
                return NSLocalizedString("login_view_password_placeholder", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Password
            static func signup_password(_: Void = ()) -> String {
                return NSLocalizedString("signup_password", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Privacy policy
            static func settingsPrivacy_policy(_: Void = ()) -> String {
                return NSLocalizedString("settings.privacy_policy", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Send email
            static func forgotpswd_send_email(_: Void = ()) -> String {
                return NSLocalizedString("forgotpswd_send_email", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Settings
            static func settingsTitle(_: Void = ()) -> String {
                return NSLocalizedString("settings.title", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Sign up
            static func login_signup_button(_: Void = ()) -> String {
                return NSLocalizedString("login_signup_button", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Sign up
            static func signup_signup_button(_: Void = ()) -> String {
                return NSLocalizedString("signup_signup_button", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Spots
            static func listTitle(_: Void = ()) -> String {
                return NSLocalizedString("list.title", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Spotting
            static func login_title(_: Void = ()) -> String {
                return NSLocalizedString("login_title", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Username
            static func forgotpswd_username(_: Void = ()) -> String {
                return NSLocalizedString("forgotpswd_username", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Username
            static func login_view_username_placeholder(_: Void = ()) -> String {
                return NSLocalizedString("login_view_username_placeholder", bundle: R.hostingBundle, comment: "")
            }

            /// Value: Username
            static func signup_username(_: Void = ()) -> String {
                return NSLocalizedString("signup_username", bundle: R.hostingBundle, comment: "")
            }

            fileprivate init() {}
        }

        fileprivate init() {}
    }

    fileprivate struct intern: Rswift.Validatable {
        fileprivate static func validate() throws {
            // There are no resources to validate
        }

        fileprivate init() {}
    }

    fileprivate class Class {}

    fileprivate init() {}
}

struct _R {
    struct nib {
        fileprivate init() {}
    }

    struct storyboard {
        struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
            typealias InitialController = UIKit.UIViewController

            let bundle = R.hostingBundle
            let name = "LaunchScreen"

            fileprivate init() {}
        }

        fileprivate init() {}
    }

    fileprivate init() {}
}
